skip_clone: false

steps:
  build:
    when:
      branch: []
      event: [manual]
    image: alpine
    commands:
      - apk add --no-cache build-base gcc curl openssl-dev gnutls-dev lmdb-dev linux-headers
      - curl -o config.c 'https://git.andrewyu.org/hax/haxircd-docs.git/plain/ci/config.c'
      - curl -o .makeopts 'https://git.andrewyu.org/hax/haxircd-docs.git/plain/ci/.makeopts'
      - make
