skip_clone: false

steps:
  build:
    when:
      branch: [master, runxiyu]
      event: [manual]
    image: archlinux
    commands:
      - pacman --noconfirm -Sy make gcc openssl gnutls curl pkgconf lmdb
      - curl -o config.c 'https://git.runxiyu.org/runxiyu/misc.git/plain/haxircd-config-example/config.c'
      - curl -o .makeopts 'https://git.runxiyu.org/runxiyu/misc.git/plain/haxircd-config-example/.makeopts'
      - make GNUTLS_SERVER=1 OPENSSL_SERVER=1 INSPIRCD2_PROTOCOL=1
