skip_clone: false

steps:
  build:
    when:
      branch: []
      event: [manual]
    image: archlinux
    commands:
      - pacman --noconfirm -Sy make gcc openssl gnutls curl pkgconf lmdb
      - curl -o config.c 'https://git.andrewyu.org/hax/haxircd-docs.git/plain/ci/config.c'
      - curl -o .makeopts 'https://git.andrewyu.org/hax/haxircd-docs.git/plain/ci/.makeopts'
      - make GNUTLS_SERVER=1 OPENSSL_SERVER=1 INSPIRCD2_PROTOCOL=1
