skip_clone: false

steps:
  build:
    image: debian:sid
    commands:
      - apt update -y
      - apt install -y build-essential libssl-dev pkg-config curl
      - curl -o config.c 'https://paste.sr.ht/blob/09d145e35ce3b058e02f5a0c664046fb66ba67e3'
      - make OPENSSL_SERVER=1 INSPIRCD2_PROTOCOL=1
